# Generated by Django 4.0.4 on 2022-05-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app1', '0002_companies_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='location',
        ),
    ]
